[project]
name = "ch16-deep-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "keras>=3.7.0",
    "matplotlib>=3.1.2",
    "numpy==1.26.4",
    "seaborn>=0.9.0",
    "tensorflow>=2.18.0",
]
